import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from google import genai

router = APIRouter(prefix="/explain", tags=["AI Explanation"])


class TransferExplanationRequest(BaseModel):
    medicine: str
    quantity: float
    distance_km: float

    source_facility: str
    source_code: str

    destination_facility: str
    destination_code: str

    scenario: dict | None = None
    reasoning: dict | None = None


@router.post("/transfer")
def explain_transfer(request: TransferExplanationRequest):
    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise HTTPException(
            status_code=500,
            detail="GEMINI_API_KEY is not configured."
        )

    client = genai.Client(api_key=api_key)

    # IMPORTANT: these must come BEFORE the prompt
    scenario = request.scenario or {}
    reasoning = request.reasoning or {}

    source = reasoning.get("source", {})
    destination = reasoning.get("destination", {})
    transfer = reasoning.get("transfer", {})

    prompt = f"""
You are the explainable AI layer of ResiliCare,
an AI-powered healthcare resource resilience platform.

Your job is to explain an EXISTING resource redistribution
decision generated by ResiliCare's optimization engine.

Do not invent values.
Do not estimate missing values.
Use only the evidence provided below.

==================================================
TRANSFER
==================================================

Medicine:
{request.medicine}

Transfer quantity:
{request.quantity:.2f} units

Transport distance:
{request.distance_km:.2f} km

Source:
{request.source_facility} ({request.source_code})

Destination:
{request.destination_facility} ({request.destination_code})


==================================================
SOURCE FACILITY EVIDENCE
==================================================

Current stock:
{source.get("current_stock", "N/A")}

Required stock:
{source.get("required_stock", "N/A")}

Available surplus:
{source.get("surplus", "N/A")}

Safety stock:
{source.get("safety_stock", "N/A")}

Daily consumption:
{source.get("daily_consumption", "N/A")}

Lead time:
{source.get("lead_time_days", "N/A")} days

Days remaining:
{source.get("days_remaining", "N/A")}

Incoming quantity:
{source.get("incoming_quantity", "N/A")}


==================================================
DESTINATION FACILITY EVIDENCE
==================================================

Current stock:
{destination.get("current_stock", "N/A")}

Required stock:
{destination.get("required_stock", "N/A")}

Projected shortage:
{destination.get("shortage", "N/A")}

Safety stock:
{destination.get("safety_stock", "N/A")}

Daily consumption:
{destination.get("daily_consumption", "N/A")}

Lead time:
{destination.get("lead_time_days", "N/A")} days

Days remaining:
{destination.get("days_remaining", "N/A")}

Incoming quantity:
{destination.get("incoming_quantity", "N/A")}


==================================================
CRISIS SCENARIO
==================================================

Demand increase:
{scenario.get("demand_increase_percent", "N/A")}%

Supply disruption:
{scenario.get("supply_disruption_days", "N/A")} days

Staff reduction:
{scenario.get("staff_reduction_percent", "N/A")}%

Bed occupancy increase:
{scenario.get("bed_occupancy_increase_percent", "N/A")}%


==================================================
EXPLANATION REQUIREMENTS
==================================================

Explain in 3 short sections:

1. WHY THIS SOURCE
Explain the source's actual surplus relative to
its required stock.

2. WHY THIS DESTINATION
Explain the destination's actual shortage relative
to its required stock.

3. WHY THIS MOVEMENT
Explain why the transfer quantity and transport
distance make this a useful operational intervention.

Use the exact numerical evidence provided.

Do not claim that the destination has a shortage
if the provided shortage is zero.

Do not claim that the source can safely transfer
more than its provided surplus.

Do not invent patient numbers, disease statistics,
inventory values, or operational facts.

Keep the explanation concise and suitable for a
professional healthcare operations dashboard.

Return only the explanation.
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt,
        )

        explanation = response.text.strip()

        return {
            "success": True,
            "explanation": explanation,
            "generated_by": "Gemini",
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Gemini explanation failed: {str(exc)}"
        )